// Wizard-generated connection point proxy class
// WARNING: This file may be regenerated by the wizard

#pragma once

template<class T>
class CProxy_IMyDeviceManagerEvents :
	public ATL::IConnectionPointImpl<T, &__uuidof(_IMyDeviceManagerEvents)>
{
public:
	
};
