#pragma once

using namespace ATL;

template <class T>
class CProxy_IOposDeviceManagerEvents : public IConnectionPointImpl<T, &__uuidof( _IOposDeviceManagerEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
